# Generated by Django 6.1.1 on 2026-09-03 14:58

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('about', models.TextField(blank=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'ordering': ['last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_author_name')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='URL 标识')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('isbn', models.CharField(blank=True, default='', max_length=20, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='定价')),
                ('price_with_tax', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.Value(Decimal('1.09'))), output_field=models.DecimalField(decimal_places=2, max_digits=10), verbose_name='含税价')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='入库时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name='books', to='catalog.author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name='book_genres', to='catalog.book', verbose_name='图书')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name='book_genres', to='catalog.genre', verbose_name='分类')),
            ],
            options={
                'verbose_name': '图书分类',
                'verbose_name_plural': '图书分类',
                'ordering': ['genre__name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', through='catalog.BookGenre', to='catalog.genre', verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False, verbose_name='借出时间')),
                ('due_date', models.DateField(verbose_name='应还日期')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name='borrows', to='catalog.book', verbose_name='图书')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DB_CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL, verbose_name='借阅人')),
            ],
            options={
                'verbose_name': '借阅记录',
                'ordering': ['-borrowed_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('book',), name='unique_active_borrow_per_book')],
            },
        ),
        migrations.AddConstraint(
            model_name='bookgenre',
            constraint=models.UniqueConstraint(fields=('book', 'genre'), name='unique_book_genre'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='book_status_idx'),
        ),
    ]
