[project]
name = "file-sync-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shihao-hub", email = "2958017271@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
file-sync-py = "file_sync_py:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
