-- ============================================================
-- 02_schema.sql —— 建表（电商风格样例库，5 张表）
-- 刻意设计的教学点（见下方各注释）：
--   1. schema 阶段只有主键 + 唯一约束，不建任何二级索引
--      —— 所有二级索引留给 04-indexes-explain 的 lab 里自己建、对比前后执行计划
--   2. PG 的外键【不会】自动创建索引（MySQL InnoDB 会）—— 阶段 4 会亲眼验证代价
--   3. orders.total 是"订单金额汇总"，由种子数据按 order_items 反算填充
--      —— 阶段 4 讲"反范式/适度冗余"时拿它举例
--   4. 状态列用 text + CHECK 而不是 enum —— 阶段 3 讲两者取舍
-- ============================================================

-- ---------- 分类表（带父子层级，供自连接 / 递归 CTE 练习） ----------
CREATE TABLE categories (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text        NOT NULL,
    parent_id integer     REFERENCES categories (id)  -- NULL = 顶级分类
);

-- ---------- 用户表（5 万行） ----------
CREATE TABLE users (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      text        NOT NULL UNIQUE,           -- 唯一约束（隐含唯一索引，是允许的）
    nickname   text        NOT NULL,
    status     text        NOT NULL DEFAULT 'active'
               CHECK (status IN ('active', 'inactive', 'banned')),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------- 商品表（5 千行） ----------
CREATE TABLE products (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text          NOT NULL,
    category_id integer       NOT NULL REFERENCES categories (id),
    price       numeric(10,2) NOT NULL CHECK (price >= 0),  -- 钱用 numeric，不用 float
    stock       integer       NOT NULL DEFAULT 0 CHECK (stock >= 0),
    tags        jsonb,                                   -- 约 5% 为 SQL NULL（阶段 3 讲 jsonb NULL）
    created_at  timestamptz  NOT NULL DEFAULT now()
);

-- ---------- 订单表（100 万行，索引教学主战场） ----------
CREATE TABLE orders (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer        NOT NULL REFERENCES users (id),   -- 注意：FK 不自动带索引！
    status     text           NOT NULL
               CHECK (status IN ('pending', 'paid', 'shipped', 'completed', 'cancelled')),
    total      numeric(12,2)  NOT NULL DEFAULT 0,
    created_at timestamptz    NOT NULL DEFAULT now(),
    paid_at    timestamptz    -- pending/cancelled 为 NULL，阶段 4 的部分索引要用到
);

-- ---------- 订单明细表（约 200 万行） ----------
CREATE TABLE order_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   bigint         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id integer        NOT NULL REFERENCES products (id),
    quantity   integer        NOT NULL CHECK (quantity > 0),
    unit_price numeric(10,2)  NOT NULL
);
